<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'registration_number' => 'LB21 ABC',
                'make' => 'Mercedes-Benz',
                'model' => 'Sprinter',
                'year' => 2021,
                'vehicle_type' => 'van',
                'color' => 'White',
                'capacity_cubic_meters' => 15,
                'max_weight_kg' => 3500,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(8),
                'insurance_expiry_date' => Carbon::now()->addMonths(5),
                'last_service_date' => Carbon::now()->subMonths(2),
                'next_service_due' => Carbon::now()->addMonths(4),
                'mileage' => 45000,
                'purchase_price' => 28000,
                'monthly_insurance' => 250,
                'monthly_finance' => 450,
                'notes' => 'Main delivery van, excellent condition',
            ],
            [
                'registration_number' => 'LB20 XYZ',
                'make' => 'Ford',
                'model' => 'Transit',
                'year' => 2020,
                'vehicle_type' => 'van',
                'color' => 'Blue',
                'capacity_cubic_meters' => 12,
                'max_weight_kg' => 3000,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(6),
                'insurance_expiry_date' => Carbon::now()->addMonths(4),
                'last_service_date' => Carbon::now()->subMonths(1),
                'next_service_due' => Carbon::now()->addMonths(5),
                'mileage' => 62000,
                'purchase_price' => 22000,
                'monthly_insurance' => 220,
                'monthly_finance' => 380,
                'notes' => 'Reliable workhorse, regular maintenance',
            ],
            [
                'registration_number' => 'LB19 DEF',
                'make' => 'Volkswagen',
                'model' => 'Crafter',
                'year' => 2019,
                'vehicle_type' => 'van',
                'color' => 'Silver',
                'capacity_cubic_meters' => 14,
                'max_weight_kg' => 3200,
                'status' => 'in_use',
                'mot_expiry_date' => Carbon::now()->addMonths(10),
                'insurance_expiry_date' => Carbon::now()->addMonths(7),
                'last_service_date' => Carbon::now()->subMonths(3),
                'next_service_due' => Carbon::now()->addMonths(3),
                'mileage' => 78000,
                'purchase_price' => 25000,
                'monthly_insurance' => 240,
                'monthly_finance' => 420,
                'notes' => 'Currently on long-term contract',
            ],
            [
                'registration_number' => 'LB22 GHI',
                'make' => 'Iveco',
                'model' => 'Daily',
                'year' => 2022,
                'vehicle_type' => 'truck',
                'color' => 'White',
                'capacity_cubic_meters' => 20,
                'max_weight_kg' => 5000,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(14),
                'insurance_expiry_date' => Carbon::now()->addMonths(9),
                'last_service_date' => Carbon::now()->subMonths(1),
                'next_service_due' => Carbon::now()->addMonths(5),
                'mileage' => 28000,
                'purchase_price' => 35000,
                'monthly_insurance' => 320,
                'monthly_finance' => 580,
                'notes' => 'New addition, perfect for large moves',
            ],
            [
                'registration_number' => 'LB18 JKL',
                'make' => 'Renault',
                'model' => 'Master',
                'year' => 2018,
                'vehicle_type' => 'van',
                'color' => 'Red',
                'capacity_cubic_meters' => 13,
                'max_weight_kg' => 3100,
                'status' => 'maintenance',
                'mot_expiry_date' => Carbon::now()->addMonths(4),
                'insurance_expiry_date' => Carbon::now()->addMonths(3),
                'last_service_date' => Carbon::now()->subMonths(4),
                'next_service_due' => Carbon::now()->addMonths(2),
                'mileage' => 95000,
                'purchase_price' => 18000,
                'monthly_insurance' => 200,
                'monthly_finance' => 0,
                'notes' => 'In for brake replacement and service',
            ],
            [
                'registration_number' => 'LB21 MNO',
                'make' => 'Peugeot',
                'model' => 'Boxer',
                'year' => 2021,
                'vehicle_type' => 'van',
                'color' => 'White',
                'capacity_cubic_meters' => 14,
                'max_weight_kg' => 3300,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(9),
                'insurance_expiry_date' => Carbon::now()->addMonths(6),
                'last_service_date' => Carbon::now()->subMonths(2),
                'next_service_due' => Carbon::now()->addMonths(4),
                'mileage' => 52000,
                'purchase_price' => 26000,
                'monthly_insurance' => 230,
                'monthly_finance' => 440,
                'notes' => 'Good fuel economy, popular with drivers',
            ],
            [
                'registration_number' => 'LB20 PQR',
                'make' => 'Citroen',
                'model' => 'Relay',
                'year' => 2020,
                'vehicle_type' => 'van',
                'color' => 'Grey',
                'capacity_cubic_meters' => 13,
                'max_weight_kg' => 3000,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(7),
                'insurance_expiry_date' => Carbon::now()->addMonths(5),
                'last_service_date' => Carbon::now()->subMonths(1),
                'next_service_due' => Carbon::now()->addMonths(5),
                'mileage' => 68000,
                'purchase_price' => 23000,
                'monthly_insurance' => 215,
                'monthly_finance' => 390,
                'notes' => 'Spacious interior, easy to drive',
            ],
            [
                'registration_number' => 'LB17 STU',
                'make' => 'Fiat',
                'model' => 'Ducato',
                'year' => 2017,
                'vehicle_type' => 'van',
                'color' => 'White',
                'capacity_cubic_meters' => 12,
                'max_weight_kg' => 2800,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(3),
                'insurance_expiry_date' => Carbon::now()->addMonths(2),
                'last_service_date' => Carbon::now()->subMonths(5),
                'next_service_due' => Carbon::now()->addMonth(1),
                'mileage' => 112000,
                'purchase_price' => 15000,
                'monthly_insurance' => 180,
                'monthly_finance' => 0,
                'notes' => 'Older but reliable, fully paid off',
            ],
            [
                'registration_number' => 'LB22 VWX',
                'make' => 'Man',
                'model' => 'TGE',
                'year' => 2022,
                'vehicle_type' => 'lorry',
                'color' => 'White',
                'capacity_cubic_meters' => 25,
                'max_weight_kg' => 7500,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(15),
                'insurance_expiry_date' => Carbon::now()->addMonths(10),
                'last_service_date' => Carbon::now()->subWeeks(2),
                'next_service_due' => Carbon::now()->addMonths(6),
                'mileage' => 18000,
                'purchase_price' => 45000,
                'monthly_insurance' => 380,
                'monthly_finance' => 720,
                'notes' => 'Heavy duty, for commercial moves',
            ],
            [
                'registration_number' => 'LB19 YZA',
                'make' => 'Nissan',
                'model' => 'NV400',
                'year' => 2019,
                'vehicle_type' => 'van',
                'color' => 'Black',
                'capacity_cubic_meters' => 13,
                'max_weight_kg' => 3100,
                'status' => 'available',
                'mot_expiry_date' => Carbon::now()->addMonths(11),
                'insurance_expiry_date' => Carbon::now()->addMonths(8),
                'last_service_date' => Carbon::now()->subMonths(2),
                'next_service_due' => Carbon::now()->addMonths(4),
                'mileage' => 71000,
                'purchase_price' => 24000,
                'monthly_insurance' => 225,
                'monthly_finance' => 410,
                'notes' => 'Executive moves, well maintained',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }

        $this->command->info('10 vehicles created successfully!');
    }
}
